/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisiteRouteImport } from './routes/visite'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MuseuRouteImport } from './routes/museu'
import { Route as InscricoesRouteImport } from './routes/inscricoes'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContribuaRouteImport } from './routes/contribua'
import { Route as CasaDaCulturaRouteImport } from './routes/casa-da-cultura'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcervoRouteImport } from './routes/acervo'
import { Route as IndexRouteImport } from './routes/index'

const VisiteRoute = VisiteRouteImport.update({
  id: '/visite',
  path: '/visite',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseuRoute = MuseuRouteImport.update({
  id: '/museu',
  path: '/museu',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricoesRoute = InscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuaRoute = ContribuaRouteImport.update({
  id: '/contribua',
  path: '/contribua',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaDaCulturaRoute = CasaDaCulturaRouteImport.update({
  id: '/casa-da-cultura',
  path: '/casa-da-cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoRoute = AcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/casa-da-cultura': typeof CasaDaCulturaRoute
  '/contribua': typeof ContribuaRoute
  '/eventos': typeof EventosRoute
  '/inscricoes': typeof InscricoesRoute
  '/museu': typeof MuseuRoute
  '/sobre': typeof SobreRoute
  '/visite': typeof VisiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/casa-da-cultura': typeof CasaDaCulturaRoute
  '/contribua': typeof ContribuaRoute
  '/eventos': typeof EventosRoute
  '/inscricoes': typeof InscricoesRoute
  '/museu': typeof MuseuRoute
  '/sobre': typeof SobreRoute
  '/visite': typeof VisiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/casa-da-cultura': typeof CasaDaCulturaRoute
  '/contribua': typeof ContribuaRoute
  '/eventos': typeof EventosRoute
  '/inscricoes': typeof InscricoesRoute
  '/museu': typeof MuseuRoute
  '/sobre': typeof SobreRoute
  '/visite': typeof VisiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acervo'
    | '/admin'
    | '/biblioteca'
    | '/casa-da-cultura'
    | '/contribua'
    | '/eventos'
    | '/inscricoes'
    | '/museu'
    | '/sobre'
    | '/visite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acervo'
    | '/admin'
    | '/biblioteca'
    | '/casa-da-cultura'
    | '/contribua'
    | '/eventos'
    | '/inscricoes'
    | '/museu'
    | '/sobre'
    | '/visite'
  id:
    | '__root__'
    | '/'
    | '/acervo'
    | '/admin'
    | '/biblioteca'
    | '/casa-da-cultura'
    | '/contribua'
    | '/eventos'
    | '/inscricoes'
    | '/museu'
    | '/sobre'
    | '/visite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcervoRoute: typeof AcervoRoute
  AdminRoute: typeof AdminRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CasaDaCulturaRoute: typeof CasaDaCulturaRoute
  ContribuaRoute: typeof ContribuaRoute
  EventosRoute: typeof EventosRoute
  InscricoesRoute: typeof InscricoesRoute
  MuseuRoute: typeof MuseuRoute
  SobreRoute: typeof SobreRoute
  VisiteRoute: typeof VisiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visite': {
      id: '/visite'
      path: '/visite'
      fullPath: '/visite'
      preLoaderRoute: typeof VisiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museu': {
      id: '/museu'
      path: '/museu'
      fullPath: '/museu'
      preLoaderRoute: typeof MuseuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricoes': {
      id: '/inscricoes'
      path: '/inscricoes'
      fullPath: '/inscricoes'
      preLoaderRoute: typeof InscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribua': {
      id: '/contribua'
      path: '/contribua'
      fullPath: '/contribua'
      preLoaderRoute: typeof ContribuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa-da-cultura': {
      id: '/casa-da-cultura'
      path: '/casa-da-cultura'
      fullPath: '/casa-da-cultura'
      preLoaderRoute: typeof CasaDaCulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo': {
      id: '/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AcervoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcervoRoute: AcervoRoute,
  AdminRoute: AdminRoute,
  BibliotecaRoute: BibliotecaRoute,
  CasaDaCulturaRoute: CasaDaCulturaRoute,
  ContribuaRoute: ContribuaRoute,
  EventosRoute: EventosRoute,
  InscricoesRoute: InscricoesRoute,
  MuseuRoute: MuseuRoute,
  SobreRoute: SobreRoute,
  VisiteRoute: VisiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
